import json

with open("university_system_interactive.ipynb", "r") as f:
    nb = json.load(f)

# The cell we want to modify is at index 2 (UI Components)
# Let's find the cell with "# --- UI Components ---"
ui_cell_idx = -1
for i, cell in enumerate(nb["cells"]):
    if cell["cell_type"] == "code" and len(cell["source"]) > 0 and "# --- UI Components ---" in cell["source"][0]:
        ui_cell_idx = i
        break

if ui_cell_idx != -1:
    source = [
        "# --- UI Components & Data Management ---\n",
        "import ipywidgets as widgets\n",
        "from IPython.display import display, clear_output\n",
        "import gc\n",
        "\n",
        "# ------------------------------------------------------------------\n",
        "# 1. Enhanced Backend Methods for UniversityApp\n",
        "# ------------------------------------------------------------------\n",
        "def _enhanced_update_student(self, s_id, new_name, new_email, new_phone, new_major):\n",
        "    student = next((s for s in self.db.students if s.student_id == s_id), None)\n",
        "    if student:\n",
        "        try:\n",
        "            if new_name: student.name = new_name\n",
        "            if new_major: student.major = new_major\n",
        "            student.update_contact(email=new_email if new_email else None, phone=new_phone if new_phone else None)\n",
        "            self.log(f\"Updated Student: {student.name} ({s_id})\", \"success\")\n",
        "        except Exception as e:\n",
        "            self.log(f\"Error updating student: {e}\", \"error\")\n",
        "UniversityApp.update_student = _enhanced_update_student\n",
        "\n",
        "def _enhanced_delete_student(self, s_id):\n",
        "    student = next((s for s in self.db.students if s.student_id == s_id), None)\n",
        "    if student:\n",
        "        # Remove from enrolled courses first\n",
        "        for course_code in list(student.enrolled_courses):\n",
        "            course = self.db.courses.get(course_code)\n",
        "            if course:\n",
        "                try: course.remove_student(student)\n",
        "                except: pass\n",
        "        self.db.students.remove(student)\n",
        "        self.log(f\"Deleted Student: {student.name} ({s_id})\", \"success\")\n",
        "UniversityApp.delete_student = _enhanced_delete_student\n",
        "\n",
        "def _create_faculty(self, name, id_val, email, phone, emp_id, dept, date):\n",
        "    try:\n",
        "        from faculty import Faculty\n",
        "        new_f = Faculty(name, f\"P{id_val}\", email, phone, emp_id, dept, date)\n",
        "        self.db.faculty_members.append(new_f)\n",
        "        # Try to add to department if exists\n",
        "        if dept in self.db.departments:\n",
        "             self.db.departments[dept].add_faculty(new_f)\n",
        "        self.log(f\"Created Faculty: {name} ({emp_id})\", \"success\")\n",
        "        return True\n",
        "    except Exception as e:\n",
        "        self.log(f\"Error creating faculty: {e}\", \"error\")\n",
        "        return False\n",
        "UniversityApp.create_faculty = _create_faculty\n",
        "\n",
        "def _delete_faculty(self, emp_id):\n",
        "    # For simplicity, we just remove from the list. In a real system, you'd handle re-assigning department heads/courses.\n",
        "    f = next((x for x in self.db.faculty_members if getattr(x, 'employee_id', '') == emp_id), None)\n",
        "    if f:\n",
        "        self.db.faculty_members.remove(f)\n",
        "        self.log(f\"Deleted Faculty: {f.name} ({emp_id})\", \"success\")\n",
        "UniversityApp.delete_faculty = _delete_faculty\n",
        "\n",
        "def _create_staff(self, name, id_val, email, phone, emp_id, role, dept):\n",
        "    try:\n",
        "        from staff import Staff\n",
        "        new_s = Staff(name, f\"P{id_val}\", email, phone, emp_id, role, dept)\n",
        "        self.db.staff_members.append(new_s)\n",
        "        self.log(f\"Created Staff: {name} ({emp_id})\", \"success\")\n",
        "        return True\n",
        "    except Exception as e:\n",
        "        self.log(f\"Error creating staff: {e}\", \"error\")\n",
        "        return False\n",
        "UniversityApp.create_staff = _create_staff\n",
        "\n",
        "def _delete_staff(self, emp_id):\n",
        "    s = next((x for x in self.db.staff_members if getattr(x, 'employee_id', '') == emp_id), None)\n",
        "    if s:\n",
        "        self.db.staff_members.remove(s)\n",
        "        self.log(f\"Deleted Staff: {s.name} ({emp_id})\", \"success\")\n",
        "UniversityApp.delete_staff = _delete_staff\n",
        "\n",
        "# Additional Refreshers\n",
        "def _refresh_faculty_dropdown(self, dropdown):\n",
        "    dropdown.options = [(f\"{getattr(f, 'name', 'Unknown')} ({getattr(f, 'employee_id', 'Unknown')})\", f) for f in getattr(self.db, 'faculty_members', [])]\n",
        "UniversityApp.refresh_faculty_dropdown = _refresh_faculty_dropdown\n",
        "\n",
        "def _refresh_staff_dropdown(self, dropdown):\n",
        "    dropdown.options = [(f\"{getattr(s, 'name', 'Unknown')} ({getattr(s, 'employee_id', 'Unknown')})\", s) for s in getattr(self.db, 'staff_members', [])]\n",
        "UniversityApp.refresh_staff_dropdown = _refresh_staff_dropdown\n",
        "\n",
        "# ------------------------------------------------------------------\n",
        "# 2. UI Construct functions\n",
        "# ------------------------------------------------------------------\n",
        "# --- Dashboard Stats ---\n",
        "dash_out = widgets.Output()\n",
        "dash_refresh_btn = widgets.Button(description=\"Refresh Stats\", icon='refresh')\n",
        "def refresh_dashboard(b=None):\n",
        "    dash_out.clear_output()\n",
        "    with dash_out:\n",
        "        print(\"=\"*40)\n",
        "        total_s = len(db.students)\n",
        "        total_f = len(getattr(db, 'faculty_members', []))\n",
        "        total_st = len(getattr(db, 'staff_members', []))\n",
        "        avg_gpa = sum(s.gpa for s in db.students) / total_s if total_s > 0 else 0.0\n",
        "        print(f\"Total Students: {total_s}\")\n",
        "        print(f\"Total Faculty:  {total_f}\")\n",
        "        print(f\"Total Staff:    {total_st}\")\n",
        "        print(f\"Average GPA:    {avg_gpa:.2f}\")\n",
        "        \n",
        "        highest = max(db.courses.values(), key=lambda c: len(getattr(c, '_enrolled_students', [])), default=None)\n",
        "        if highest:\n",
        "            print(f\"Most Popular:   {highest.course_code} ({len(getattr(highest, '_enrolled_students', []))} students)\")\n",
        "        print(\"=\"*40)\n",
        "dash_refresh_btn.on_click(refresh_dashboard)\n",
        "dash_box = widgets.VBox([widgets.HTML(\"<h3>System Overview</h3>\"), dash_refresh_btn, dash_out])\n",
        "\n",
        "# --- Manage Students ---\n",
        "manage_s_dropdown = widgets.Dropdown(description=\"Select:\")\n",
        "s_name = widgets.Text(description=\"Name:\")\n",
        "s_id = widgets.Text(description=\"Person ID:\")\n",
        "s_student_id = widgets.Text(description=\"Student ID:\")\n",
        "s_email = widgets.Text(description=\"Email:\")\n",
        "s_phone = widgets.Text(description=\"Phone:\")\n",
        "s_major = widgets.Text(description=\"Major:\")\n",
        "s_date = widgets.Text(description=\"Date:\", value=\"2024-01-01\")\n",
        "\n",
        "s_add_btn = widgets.Button(description=\"Add New\", button_style='success', icon='plus')\n",
        "s_upd_btn = widgets.Button(description=\"Update Selected\", button_style='warning', icon='edit')\n",
        "s_del_btn = widgets.Button(description=\"Delete Selected\", button_style='danger', icon='trash')\n",
        "\n",
        "def on_ms_drop(change):\n",
        "    s = manage_s_dropdown.value\n",
        "    if s:\n",
        "        s_name.value = s.name\n",
        "        s_id.value = getattr(s, '_person_id', '')\n",
        "        s_student_id.value = s.student_id\n",
        "        s_email.value = s.email\n",
        "        s_phone.value = s.phone\n",
        "        s_major.value = getattr(s, 'major', '')\n",
        "        s_date.value = getattr(s, 'enrollment_date', '')\n",
        "\n",
        "def refresh_all_student_dropdowns():\n",
        "    app.refresh_student_dropdown(manage_s_dropdown)\n",
        "    if 'enroll_s_drop' in globals(): app.refresh_student_dropdown(enroll_s_drop)\n",
        "    if 'profile_s_drop' in globals(): app.refresh_student_dropdown(profile_s_drop)\n",
        "    refresh_dashboard()\n",
        "\n",
        "manage_s_dropdown.observe(on_ms_drop, names='value')\n",
        "\n",
        "def on_s_add(b):\n",
        "    if app.create_student(s_name.value, s_id.value, s_email.value, s_phone.value, s_student_id.value, s_major.value, s_date.value):\n",
        "        refresh_all_student_dropdowns()\n",
        "        \n",
        "def on_s_upd(b):\n",
        "    s = manage_s_dropdown.value\n",
        "    if s:\n",
        "        app.update_student(s.student_id, s_name.value, s_email.value, s_phone.value, s_major.value)\n",
        "        refresh_all_student_dropdowns()\n",
        "\n",
        "def on_s_del(b):\n",
        "    s = manage_s_dropdown.value\n",
        "    if s:\n",
        "        app.delete_student(s.student_id)\n",
        "        refresh_all_student_dropdowns()\n",
        "\n",
        "s_add_btn.on_click(on_s_add)\n",
        "s_upd_btn.on_click(on_s_upd)\n",
        "s_del_btn.on_click(on_s_del)\n",
        "\n",
        "manage_s_box = widgets.VBox([\n",
        "    widgets.HTML(\"<h4>Manage Students</h4>\"),\n",
        "    manage_s_dropdown, widgets.HTML(\"<hr>\"),\n",
        "    s_name, s_id, s_student_id, s_email, s_phone, s_major, s_date,\n",
        "    widgets.HBox([s_add_btn, s_upd_btn, s_del_btn])\n",
        "])\n",
        "\n",
        "# --- Manage Faculty ---\n",
        "manage_f_dropdown = widgets.Dropdown(description=\"Select:\")\n",
        "f_name = widgets.Text(description=\"Name:\")\n",
        "f_id = widgets.Text(description=\"Person ID:\")\n",
        "f_emp_id = widgets.Text(description=\"Emp ID:\")\n",
        "f_email = widgets.Text(description=\"Email:\")\n",
        "f_phone = widgets.Text(description=\"Phone:\")\n",
        "f_dept = widgets.Text(description=\"Dept:\")\n",
        "f_date = widgets.Text(description=\"Date:\", value=\"2020-01-01\")\n",
        "\n",
        "f_add_btn = widgets.Button(description=\"Add New\", button_style='success', icon='plus')\n",
        "f_del_btn = widgets.Button(description=\"Delete Selected\", button_style='danger', icon='trash')\n",
        "\n",
        "def on_mf_drop(change):\n",
        "    f = manage_f_dropdown.value\n",
        "    if f:\n",
        "        f_name.value = f.name\n",
        "        f_id.value = getattr(f, '_person_id', '')\n",
        "        f_emp_id.value = getattr(f, 'employee_id', '')\n",
        "        f_email.value = f.email\n",
        "        f_phone.value = f.phone\n",
        "        f_dept.value = getattr(f, 'department', '')\n",
        "        f_date.value = getattr(f, 'hire_date', '')\n",
        "manage_f_dropdown.observe(on_mf_drop, names='value')\n",
        "\n",
        "def refresh_all_fac_dropdowns():\n",
        "    app.refresh_faculty_dropdown(manage_f_dropdown)\n",
        "    refresh_dashboard()\n",
        "    \n",
        "def on_f_add(b):\n",
        "    if app.create_faculty(f_name.value, f_id.value, f_email.value, f_phone.value, f_emp_id.value, f_dept.value, f_date.value):\n",
        "        refresh_all_fac_dropdowns()\n",
        "def on_f_del(b):\n",
        "    f = manage_f_dropdown.value\n",
        "    if f:\n",
        "        app.delete_faculty(getattr(f, 'employee_id', ''))\n",
        "        refresh_all_fac_dropdowns()\n",
        "f_add_btn.on_click(on_f_add)\n",
        "f_del_btn.on_click(on_f_del)\n",
        "\n",
        "manage_f_box = widgets.VBox([\n",
        "    widgets.HTML(\"<h4>Manage Faculty</h4>\"),\n",
        "    manage_f_dropdown, widgets.HTML(\"<hr>\"),\n",
        "    f_name, f_id, f_emp_id, f_email, f_phone, f_dept, f_date,\n",
        "    widgets.HBox([f_add_btn, f_del_btn])\n",
        "])\n",
        "\n",
        "# --- Manage Staff ---\n",
        "manage_st_dropdown = widgets.Dropdown(description=\"Select:\")\n",
        "st_name = widgets.Text(description=\"Name:\")\n",
        "st_id = widgets.Text(description=\"Person ID:\")\n",
        "st_emp_id = widgets.Text(description=\"Emp ID:\")\n",
        "st_email = widgets.Text(description=\"Email:\")\n",
        "st_phone = widgets.Text(description=\"Phone:\")\n",
        "st_role = widgets.Text(description=\"Role:\")\n",
        "st_dept = widgets.Text(description=\"Dept:\")\n",
        "\n",
        "st_add_btn = widgets.Button(description=\"Add New\", button_style='success', icon='plus')\n",
        "st_del_btn = widgets.Button(description=\"Delete Selected\", button_style='danger', icon='trash')\n",
        "\n",
        "def on_mst_drop(change):\n",
        "    s = manage_st_dropdown.value\n",
        "    if s:\n",
        "        st_name.value = s.name\n",
        "        st_id.value = getattr(s, '_person_id', '')\n",
        "        st_emp_id.value = getattr(s, 'employee_id', '')\n",
        "        st_email.value = s.email\n",
        "        st_phone.value = s.phone\n",
        "        st_role.value = getattr(s, 'role', '')\n",
        "        st_dept.value = getattr(s, 'department', '')\n",
        "manage_st_dropdown.observe(on_mst_drop, names='value')\n",
        "\n",
        "def refresh_all_st_dropdowns():\n",
        "    app.refresh_staff_dropdown(manage_st_dropdown)\n",
        "    refresh_dashboard()\n",
        "\n",
        "def on_st_add(b):\n",
        "    if app.create_staff(st_name.value, st_id.value, st_email.value, st_phone.value, st_emp_id.value, st_role.value, st_dept.value):\n",
        "        refresh_all_st_dropdowns()\n",
        "def on_st_del(b):\n",
        "    s = manage_st_dropdown.value\n",
        "    if s:\n",
        "        app.delete_staff(getattr(s, 'employee_id', ''))\n",
        "        refresh_all_st_dropdowns()\n",
        "st_add_btn.on_click(on_st_add)\n",
        "st_del_btn.on_click(on_st_del)\n",
        "\n",
        "manage_st_box = widgets.VBox([\n",
        "    widgets.HTML(\"<h4>Manage non-academic Staff</h4>\"),\n",
        "    manage_st_dropdown, widgets.HTML(\"<hr>\"),\n",
        "    st_name, st_id, st_emp_id, st_email, st_phone, st_role, st_dept,\n",
        "    widgets.HBox([st_add_btn, st_del_btn])\n",
        "])\n",
        "\n",
        "# --- Tab: Data Management (Accordion) ---\n",
        "manage_accordion = widgets.Accordion(children=[manage_s_box, manage_f_box, manage_st_box])\n",
        "manage_accordion.set_title(0, 'Students')\n",
        "manage_accordion.set_title(1, 'Faculty')\n",
        "manage_accordion.set_title(2, 'Staff')\n",
        "\n",
        "# --- Enrollment & Grading Tab ---\n",
        "enroll_s_drop = widgets.Dropdown(description=\"Student:\")\n",
        "enroll_c_drop = widgets.Dropdown(description=\"Course:\")\n",
        "enroll_btn = widgets.Button(description=\"Enroll\", button_style='success', icon='check')\n",
        "grade_input = widgets.BoundedFloatText(value=0.0, min=0.0, max=4.0, step=0.1, description=\"Grade:\")\n",
        "grade_btn = widgets.Button(description=\"Assign Grade\", button_style='warning', icon='graduation-cap')\n",
        "\n",
        "def on_enroll_click(b):\n",
        "    s, c = enroll_s_drop.value, enroll_c_drop.value\n",
        "    if s and c:\n",
        "        try:\n",
        "            c.add_student(s)\n",
        "            app.log(f\"Enrolled {s.name} in {c.course_code}\", \"success\")\n",
        "            refresh_dashboard()\n",
        "            if 'profile_s_drop' in globals() and profile_s_drop.value == s: profile_s_drop.value = s # trigger re-render\n",
        "        except Exception as e: app.log(f\"{e}\", \"error\")\n",
        "enroll_btn.on_click(on_enroll_click)\n",
        "\n",
        "def on_grade_click(b):\n",
        "    s, c = enroll_s_drop.value, enroll_c_drop.value\n",
        "    if s and c:\n",
        "        app.assign_grade(s, c.course_code, grade_input.value)\n",
        "        refresh_dashboard()\n",
        "grade_btn.on_click(on_grade_click)\n",
        "\n",
        "enroll_box = widgets.VBox([widgets.HTML(\"<h3>Enrollment & Grades</h3>\"), enroll_s_drop, enroll_c_drop, enroll_btn, widgets.HTML(\"<hr>\"), grade_input, grade_btn])\n",
        "\n",
        "# --- Views Tab (Profiles & Course details) ---\n",
        "profile_s_drop = widgets.Dropdown(description=\"Student:\")\n",
        "profile_out = widgets.Output()\n",
        "def show_s_profile(change):\n",
        "    profile_out.clear_output()\n",
        "    s = profile_s_drop.value\n",
        "    if s:\n",
        "        with profile_out:\n",
        "            info = s.get_info()\n",
        "            print(f\"Name: {info.get('name', 'N/A')}\\nEmail: {info.get('email', '')}\\nMajor: {info.get('major', '')}\")\n",
        "            print(f\"GPA: {s.gpa:.2f} ({s.get_academic_status()})\")\n",
        "            print(\"Enrolled:\", ', '.join(s.enrolled_courses) if s.enrolled_courses else \"None\")\n",
        "            for c, g in s.grades.items(): print(f\"  > {c}: {g}\")\n",
        "profile_s_drop.observe(show_s_profile, names='value')\n",
        "\n",
        "details_c_drop = widgets.Dropdown(description=\"Course:\")\n",
        "course_out = widgets.Output()\n",
        "def show_c_details(change):\n",
        "    course_out.clear_output()\n",
        "    c = details_c_drop.value\n",
        "    if c:\n",
        "        with course_out:\n",
        "            print(f\"Course: {c.course_code} - {c.course_name}\")\n",
        "            inst = getattr(c, '_instructor', None)\n",
        "            print(f\"Credits: {getattr(c, '_credits', 'N/A')} | Instructor: {getattr(inst, 'name', 'None')}\")\n",
        "            enrolled = getattr(c, '_enrolled_students', [])\n",
        "            print(f\"Enrollment: {len(enrolled)} / {c.max_capacity}\")\n",
        "            for s in enrolled: print(f\"  - {s.name} ({s.student_id})\")\n",
        "details_c_drop.observe(show_c_details, names='value')\n",
        "\n",
        "views_accordion = widgets.Accordion(children=[\n",
        "    widgets.VBox([profile_s_drop, profile_out]), \n",
        "    widgets.VBox([details_c_drop, course_out])\n",
        "])\n",
        "views_accordion.set_title(0, 'Student Profiles')\n",
        "views_accordion.set_title(1, 'Course Details')\n",
        "\n",
        "# --- Demos Tab ---\n",
        "demo_a_btn = widgets.Button(description=\"A. Hierarchy\", icon='play')\n",
        "demo_b_btn = widgets.Button(description=\"B&C. Courses\", icon='play')\n",
        "demo_d_btn = widgets.Button(description=\"D. Polymorphism\", icon='play')\n",
        "demo_e_btn = widgets.Button(description=\"E. Departments\", icon='play')\n",
        "demo_a_btn.on_click(lambda b: [app.log(\"Running Demo A...\", \"demo\"), demo_class_hierarchy(printer=app.demo_printer)])\n",
        "demo_b_btn.on_click(lambda b: [app.log(\"Running Demo B&C...\", \"demo\"), demo_student_course_management(printer=app.demo_printer)])\n",
        "demo_d_btn.on_click(lambda b: [app.log(\"Running Demo D...\", \"demo\"), demo_polymorphism(printer=app.demo_printer)])\n",
        "demo_e_btn.on_click(lambda b: [app.log(\"Running Demo E...\", \"demo\"), demo_department_and_courses(printer=app.demo_printer)])\n",
        "demo_box = widgets.VBox([widgets.HTML(\"<h3>Run Outputs to Log</h3>\"), widgets.HBox([demo_a_btn, demo_b_btn, demo_d_btn, demo_e_btn])])\n",
        "\n",
        "# --- Initialization --- \n",
        "refresh_all_student_dropdowns()\n",
        "refresh_all_fac_dropdowns()\n",
        "refresh_all_st_dropdowns()\n",
        "app.refresh_course_dropdown(enroll_c_drop)\n",
        "app.refresh_course_dropdown(details_c_drop)\n",
        "if manage_s_dropdown.value: on_ms_drop(None)\n",
        "if manage_f_dropdown.value: on_mf_drop(None)\n",
        "if manage_st_dropdown.value: on_mst_drop(None)\n",
        "if profile_s_drop.value: show_s_profile(None)\n",
        "if details_c_drop.value: show_c_details(None)\n",
        "refresh_dashboard()\n",
        "\n",
        "# --- Main Layout Assembly ---\n",
        "main_tabs = widgets.Tab([dash_box, manage_accordion, enroll_box, views_accordion, demo_box])\n",
        "main_tabs.set_title(0, 'Dashboard')\n",
        "main_tabs.set_title(1, 'Manage Data')\n",
        "main_tabs.set_title(2, 'Enrollment')\n",
        "main_tabs.set_title(3, 'Views')\n",
        "main_tabs.set_title(4, 'Demos')\n",
        "\n",
        "main_ui = widgets.VBox([main_tabs, widgets.HTML(\"<hr><h3>Activity Log</h3>\"), app.log_container])\n",
        "display(main_ui)\n"
    ]

    nb["cells"][ui_cell_idx]["source"] = source

with open("university_system_interactive.ipynb", "w") as f:
    json.dump(nb, f, indent=4)

print("Notebook modified successfully.")
